### ISSUE TITLE
Debian Package

### ISSUE THREAD

**Issue by hfhchan** [tamcy/chiron-sans-hk#8]
Any plans to add the font as a Debian Package?

**Comment by tamcy** [comment]
Thanks for the question.

While I welcome such a package and understand the benefit of it, there is currently no plan, at least in short term, to create a `.deb` package of the font, simply because of the limited resources (i.e. time) I have. If possible, it would be better to leave it to someone who is more familiar with the matter. The same applies to other packaging formats.

That said, I may look into it when the font reaches its stable stage (which I think is near) and still no one is interested in releasing such a package.

**Comment by hfhchan** [comment]
@sgalal 有無興趣 🙇🏻‍♂️
